name: pseduoapp
description: A new Flutter project.

dependencies:
  html: any
  http_server: any
  twitter: "^0.5.2"
  crypto: any
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - icons/twitterlogo.jpg
    - icons/youtube.png
    - icons/twitch.png
    - icons/merch.png
    - icons/youtube_watch.png
    - images/560-1.jpg
    - images/561-1.jpg
    - images/562-1.jpg
    - images/563-1.jpg
    - images/564-1.jpg
    - images/564-2.jpg
    - images/564-3.jpg
    - images/564-4.jpg
    - images/564-5.jpg
    - images/565-1.jpg
    - images/565-2.jpg
    - images/565-3.jpg
    - images/565-4.jpg
    - images/566-1.jpg
    - images/566-2.jpg
    - images/566-3.jpg
    - images/566-4.jpg
    - images/567-1.jpg
    - images/567-2.jpg
    - images/567-3.jpg
    - images/567-4.jpg
    - images/568-1.jpg
    - images/568-2.jpg
    - images/568-3.jpg
    - images/568-4.jpg
    - images/569-1.jpg
    - images/569-2.jpg
    - images/569-3.jpg
    - images/569-4.jpg
    - images/570-1.jpg
    - images/571-1.jpg
    - images/571-2.jpg
    - images/571-3.jpg
    - images/571-4.jpg
    - images/572-1.jpg
    - images/572-2.jpg
    - images/572-3.jpg
    - images/572-4.jpg
    - images/573-1.jpg
    - images/573-2.jpg
    - images/573-3.jpg
    - images/573-4.jpg
    - images/574-1.jpg
    - images/574-2.jpg
    - images/574-3.jpg
    - images/574-4.jpg
    - images/574-5.jpg
    - images/575-1.jpg
    - images/575-2.jpg
    - images/575-3.jpg
    - images/575-4.jpg
    - images/576-1.jpg
    - images/576-2.jpg
    - images/576-3.jpg
    - images/576-4.jpg
    - images/577-1.jpg
    - images/577-2.jpg
    - images/577-3.jpg
    - images/577-4.jpg
    - images/578-1.jpg
    - images/merch_banner.png
    - images/merch_banner2.png
    - images/youtube_banner.png
  fonts:
    - family: HelveticaNeueMed
      fonts:
        - asset: fonts/HelveticaNeueMed.ttf
          weight: 100
    - family: IntegralCF
      fonts:
        - asset: fonts/IntegralCF-HeavyOblique.otf
          weight: 100
    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf
          weight: 100
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 100
    - family: HanSans
      fonts:
        - asset: fonts/BlackHanSans-Regular.ttf
          weight: 100

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
